services:
  web:
    build: webapp/
    container_name: webapp
    expose:
      - '8080'
    
  nginx:
    build: nginx/
    container_name: nginx
    ports:
      - '80:80'
    depends_on:
      - web
